name: Bug report
description: Report a reproducible bug in npmvulncheck
title: "[Bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.
        Please include enough details for maintainers to reproduce quickly.
  - type: input
    id: version
    attributes:
      label: npmvulncheck version
      description: Output of `npmvulncheck version` or package version
      placeholder: "0.1.1"
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: "v20.19.0"
    validations:
      required: true
  - type: dropdown
    id: lockfile
    attributes:
      label: Lockfile / package manager
      options:
        - package-lock.json (npm)
        - npm-shrinkwrap.json (npm)
        - pnpm-lock.yaml (pnpm)
        - yarn.lock (yarn)
        - No lockfile
    validations:
      required: true
  - type: textarea
    id: command
    attributes:
      label: Command
      description: Exact command and options that trigger the bug
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Minimal reproduction
      description: Steps or repository URL
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Redact secrets before sharing
      render: text
